# Generated by Django 4.2.1 on 2024-10-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=300, verbose_name='Yil/oy/kun  vaqtlari')),
                ('day', models.CharField(max_length=300, verbose_name='kun  vaqtlari')),
                ('time', models.CharField(max_length=300, verbose_name=' vaqtlari')),
                ('host', models.CharField(max_length=300, verbose_name='host nomi')),
                ('proxy', models.CharField(max_length=300, verbose_name='host nomi')),
                ('ip', models.CharField(max_length=300, verbose_name='ip nomi')),
                ('datetime', models.CharField(max_length=300, verbose_name='  vaqtlari')),
                ('type', models.CharField(max_length=300, verbose_name='type turi')),
                ('type_ip', models.CharField(max_length=300, verbose_name=' type ipp addreslari')),
                ('response', models.CharField(max_length=300, verbose_name='qaytgan javoblar_')),
            ],
            options={
                'verbose_name': 'Xatolik chiqgan logslar_',
            },
        ),
    ]
